config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'

  resources :poke_eggs do
    resources :purchases, only: [:new, :create]
  end
  resources :users
  resources :purchases, only: [:show, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poke_egg.rb
class PokeEgg < ApplicationRecord
  belongs_to :user
  has_many :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :poke_egg
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :poke_eggs
  has_many :purchases
  has_many :poke_eggs, through: :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/poke_eggs_controller.rb
class PokeEggsController < ApplicationController

  def index
    @poke_eggs = PokeEgg.all
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/poke_eggs_helper.rb
module PokeEggsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokegg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-pages">
  <div class="pokemon-logo">
    <%= image_tag "pokemon.jpg"  %>
    <%= link_to "Buy your egg", poke_eggs_path, class: "btn btn-primary"  %>
  </div>
  <div class="pikachu-image">
    <%= image_tag "pikachu.png" %>
  </div>
  <div class= "oeufs-pokemon ">
      <%= image_tag "oeuf-pokemon.jpg" %>
      <%= image_tag "oeuf-pokemon.jpg" %>
      <%= image_tag "oeuf-pokemon.jpg" %>
      <%= image_tag "oeuf-pokemon.jpg" %>
      <%= image_tag "oeuf-pokemon.jpg" %>
  </div>
</div>

app/views/poke_eggs/index.html.erb
<% @poke_eggs.each do |pokemon| %>
  <%= pokemon.name %>
<% end %>